application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '86400000'
      refresh-token:
        expiration: '604800000'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#    show-sql: true
  mail:
    username: mohammadmashhour24@gmail.com
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: fzkq khke mbxe yukj
  application:
    name: ProjectTraninng
  servlet:
    multipart:
      max-file-size: 100MB
      enabled: 'true'
      max-request-size: 100MB
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: ${DB_DRIVER}
logging:
  level:
    com:
      example: DEBUG
    root: INFO
server:
  port: ${PORT:8080}
  spring:
    resources:
      cache:
        period: 0
